version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '27077:27017'
  node:
    container_name: backend
    build: 
      context: '../../idev-backend'
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEV_DB_HOST=host.docker.internal
      - DEV_DB_PORT=27077
    ports: 
      - 3066:3066
    links:
      - mongo